const players = [
  {
    firstName: "Nick",
    lastName: "Abruzzese",
    position: "C",
    age: 25,
    height: "5-11",
    weight: "183",
    draftPosition: "2019 TOR 4th (124)",
    photo: "imgs/abruzzese.png",
    funFact: "Made his NHL debut with the Leafs in 2024-25.",
  },
  {
    firstName: "Artur",
    lastName: "Akhtyamov",
    position: "C",
    age: 21,
    height: "6-1",
    weight: "185",
    draftPosition: "Undrafted",
    photo: "imgs/akhtyamov.png",
    funFact: "Young prospect signed to Toronto’s system in 2024.",
  },
  {
    firstName: "Matt",
    lastName: "Benning",
    position: "RD",
    age: 30,
    height: "6-1",
    weight: "203",
    draftPosition: "2012 BOS 6th (175)",
    photo: "imgs/benning.png",
    funFact: "Signed from Sharks in October 2024.",
  },
  {
    firstName: "Simon",
    lastName: "Benoit",
    position: "LD",
    age: 26,
    height: "6-4",
    weight: "211",
    draftPosition: "2017 ANA 6th (171)",
    photo: "imgs/benoit.png",
    funFact: "Added physicality and offensive upside from the blue line.",
  },
  {
    firstName: "Brandon",
    lastName: "Carlo",
    position: "LD",
    age: 28,
    height: "6-4",
    weight: "212",
    draftPosition: "2015 BOS 2nd (37)",
    photo: "imgs/carlo.png",
    funFact: "Known for his strong defensive play and shot-blocking.",
  },
  {
    firstName: "Max",
    lastName: "Domi",
    position: "LW",
    age: 29,
    height: "5-10",
    weight: "209",
    draftPosition: "2013 ARI 1st (12)",
    photo: "imgs/domi.png",
    funFact: "Brought grit and 76 penalty minutes in 2024-25.",
  },
  {
    firstName: "Oliver",
    lastName: "Ekman-Larsson",
    position: "LD",
    age: 33,
    height: "6-2",
    weight: "192",
    draftPosition: "2009 PHX 1st (6)",
    photo: "imgs/ekman-larsson.png",
    funFact:
      "Joined Leafs in 2024 after a long career with Arizona and Florida.",
  },
  {
    firstName: "Dennis",
    lastName: "Hildeby",
    position: "G",
    age: 23,
    height: "6-4",
    weight: "176",
    draftPosition: "Undrafted",
    photo: "imgs/hildeby.png",
    funFact: "Young goalie prospect with a big wingspan.",
  },
  {
    firstName: "Roni",
    lastName: "Hirvonen",
    position: "C",
    age: 22,
    height: "5-11",
    weight: "176",
    draftPosition: "2019 TOR 2nd (59)",
    photo: "imgs/hirvonen.png",
    funFact: "Known for his speed and playmaking skills.",
  },
  {
    firstName: "Pontus",
    lastName: "Holmberg",
    position: "LW",
    age: 27,
    height: "5-10",
    weight: "185",
    draftPosition: "Undrafted",
    photo: "imgs/holmberg.png",
    funFact: "Swedish forward who joined the Leafs in 2024.",
  },
  {
    firstName: "Calle",
    lastName: "Jarnkrok",
    position: "C",
    age: 33,
    height: "6-0",
    weight: "191",
    draftPosition: "2010 DET 2nd (51)",
    photo: "imgs/jarnkrok.png",
    funFact: "Reliable two-way center signed in 2024.",
  },
  {
    firstName: "Reese",
    lastName: "Johnson",
    position: "C",
    age: 26,
    height: "6-1",
    weight: "193",
    draftPosition: "2016 CHI 7th (198)",
    photo: "imgs/johnson.png",
    funFact: "Added grit after joining Leafs midseason.",
  },
  {
    firstName: "David",
    lastName: "Kampf",
    position: "C",
    age: 30,
    height: "6-2",
    weight: "193",
    draftPosition: "2015 CHI 5th (150)",
    photo: "imgs/kampf.png",
    funFact: "Effective defensive center with strong faceoff skills.",
  },
  {
    firstName: "Matthew",
    lastName: "Knies",
    position: "LW",
    age: 22,
    height: "6-3",
    weight: "227",
    draftPosition: "2021 TOR 2nd (57)",
    photo: "imgs/knies.png",
    funFact: "Scored his first NHL hat trick in 2025.",
  },
  {
    firstName: "Mikko",
    lastName: "Kokkonen",
    position: "LD",
    age: 23,
    height: "6-3",
    weight: "193",
    draftPosition: "2020 TOR 2nd (51)",
    photo: "imgs/kokkonen.png",
    funFact: "Promising young defenseman developing in the Leafs system.",
  },
  {
    firstName: "Scott",
    lastName: "Laughton",
    position: "C",
    age: 30,
    height: "6-1",
    weight: "191",
    draftPosition: "2012 PHI 1st (20)",
    photo: "imgs/laughton.png",
    funFact: "Joined Leafs in March 2025 from the Flyers.",
  },
  {
    firstName: "Steven",
    lastName: "Lorentz",
    position: "C",
    age: 28,
    height: "6-4",
    weight: "216",
    draftPosition: "2015 CAR 7th (186)",
    photo: "imgs/lorentz.png",
    funFact: "Stanley Cup winner with Florida in 2024.",
  },
  {
    firstName: "Mitch",
    lastName: "Marner",
    position: "RW",
    age: 27,
    height: "6-0",
    weight: "180",
    draftPosition: "2015 TOR 1st (4)",
    photo: "imgs/marner.png",
    funFact: "Led Leafs with 102 points in 2024-25.",
  },
  {
    firstName: "Auston",
    lastName: "Matthews",
    position: "C",
    age: 27,
    height: "6-3",
    weight: "217",
    draftPosition: "2016 TOR 1st (1)",
    photo: "imgs/matthews.png",
    funFact: "First American-born captain in Leafs history.",
  },
  {
    firstName: "Jake",
    lastName: "McCabe",
    position: "LD",
    age: 31,
    height: "6-1",
    weight: "212",
    draftPosition: "2012 BUF 2nd (44)",
    photo: "imgs/mccabe.png",
    funFact: "Recorded 23 points in 2024-25.",
  },
  {
    firstName: "Bobby",
    lastName: "McMann",
    position: "RW",
    age: 28,
    height: "6-2",
    weight: "215",
    draftPosition: "2019 TOR 4th (124)",
    photo: "imgs/mcmann.png",
    funFact: "Scored 20 goals in 2024-25 season.",
  },
  {
    firstName: "Dakota",
    lastName: "Mermis",
    position: "RD",
    age: 30,
    height: "6-1",
    weight: "197",
    draftPosition: "Undrafted",
    photo: "imgs/mermis.png",
    funFact: "Veteran depth defenseman.",
  },
  {
    firstName: "Matt",
    lastName: "Murray",
    position: "G",
    age: 29,
    height: "6-4",
    weight: "185",
    draftPosition: "2012 PIT 3rd (83)",
    photo: "imgs/murray.png",
    funFact: "Two-time Stanley Cup champion goalie.",
  },
  {
    firstName: "Philippe",
    lastName: "Myers",
    position: "RD",
    age: 28,
    height: "6-5",
    weight: "219",
    draftPosition: "2015 PHI 4th (122)",
    photo: "imgs/myers.png",
    funFact: "Joined Leafs midseason in 2025 from Tampa Bay.",
  },
  {
    firstName: "Topi",
    lastName: "Niemela",
    position: "LD",
    age: 21,
    height: "6-2",
    weight: "187",
    draftPosition: "2019 TOR 3rd (64)",
    photo: "imgs/niemela.png",
    funFact: "Promising young Finnish defenseman.",
  },
  {
    firstName: "Alex",
    lastName: "Nylander",
    position: "RW",
    age: 26,
    height: "6-1",
    weight: "196",
    draftPosition: "2016 BUF 1st (8)",
    photo: "imgs/a-nylander.png",
    funFact: "Younger brother of William Nylander.",
  },
  {
    firstName: "William",
    lastName: "Nylander",
    position: "RW",
    age: 28,
    height: "6-0",
    weight: "202",
    draftPosition: "2014 TOR 1st (8)",
    photo: "imgs/w-nylander.png",
    funFact: "Scored 45 goals in the regular season.",
  },
  {
    firstName: "Max",
    lastName: "Pacioretty",
    position: "LW",
    age: 34,
    height: "6-0",
    weight: "213",
    draftPosition: "2007 MTL 1st (22)",
    photo: "imgs/pacioretty.png",
    funFact: "Veteran scorer and team leader.",
  },
  {
    firstName: "Jacob",
    lastName: "Quillan",
    position: "RW",
    age: 24,
    height: "6-1",
    weight: "195",
    draftPosition: "Undrafted",
    photo: "imgs/quillan.png",
    funFact: "Made NHL debut in 2024-25.",
  },
  {
    firstName: "Ryan",
    lastName: "Reaves",
    position: "RW",
    age: 36,
    height: "6-2",
    weight: "215",
    draftPosition: "2005 STL 4th (156)",
    photo: "imgs/reaves.png",
    funFact: "Known as one of the toughest enforcers in the league.",
  },
  {
    firstName: "Morgan",
    lastName: "Rielly",
    position: "LD",
    age: 30,
    height: "5-11",
    weight: "194",
    draftPosition: "2012 TOR 1st (5)",
    photo: "imgs/rielly.png",
    funFact: "Longest-tenured Leaf defenseman and team captain.",
  },
  {
    firstName: "Marshall",
    lastName: "Rifai",
    position: "RD",
    age: 20,
    height: "6-2",
    weight: "195",
    draftPosition: "Undrafted",
    photo: "imgs/rifai.png",
    funFact: "Young prospect recently signed.",
  },
  {
    firstName: "Nicholas",
    lastName: "Robertson",
    position: "RW",
    age: 22,
    height: "6-0",
    weight: "175",
    draftPosition: "2019 TOR 1st (53)",
    photo: "imgs/robertson.png",
    funFact: "Coming off injury but shows high offensive upside.",
  },
  {
    firstName: "Alex",
    lastName: "Steeves",
    position: "C",
    age: 24,
    height: "6-1",
    weight: "190",
    draftPosition: "Undrafted",
    photo: "imgs/steeves.png",
    funFact: "Signed as a free agent in 2024.",
  },
  {
    firstName: "Anthony",
    lastName: "Stolarz",
    position: "G",
    age: 29,
    height: "6-4",
    weight: "202",
    draftPosition: "2012 PHI 2nd (45)",
    photo: "imgs/stolarz.png",
    funFact: "Experienced backup goalie.",
  },
  {
    firstName: "Christopher",
    lastName: "Tanev",
    position: "RD",
    age: 34,
    height: "6-1",
    weight: "190",
    draftPosition: "Undrafted",
    photo: "imgs/tanev.png",
    funFact: "Known for his smooth skating and defense.",
  },
  {
    firstName: "John",
    lastName: "Tavares",
    position: "C",
    age: 32,
    height: "6-1",
    weight: "197",
    draftPosition: "2009 NYI 1st (1)",
    photo: "imgs/tavares.png",
    funFact: "Leafs captain since 2019 and franchise icon.",
  },
  {
    firstName: "William",
    lastName: "Villeneuve",
    position: "LD",
    age: 20,
    height: "6-0",
    weight: "185",
    draftPosition: "Undrafted",
    photo: "imgs/villeneuve.png",
    funFact: "Young defenseman in the Leafs system.",
  },
  {
    firstName: "Cade",
    lastName: "Webber",
    position: "LD",
    age: 21,
    height: "6-0",
    weight: "190",
    draftPosition: "Undrafted",
    photo: "imgs/webber.png",
    funFact: "Promising young defender signed recently.",
  },
  {
    firstName: "Joseph",
    lastName: "Woll",
    position: "G",
    age: 26,
    height: "6-4",
    weight: "205",
    draftPosition: "2017 TOR 5th (136)",
    photo: "imgs/woll.png",
    funFact: "Served as backup goalie for Leafs since 2021.",
  },
];
