const players = [
  {
    firstName: "Nick",
    lastName: "Abruzzese",
    position: "F",
    age: 25,
    height: "5-11",
    weight: "183",
    draftPosition: "2019 TOR 4th (124)",
    photo: "imgs/abruzzese.png",
  },
  {
    firstName: "Artur",
    lastName: "Akhtyamov",
    position: "G",
    age: 23,
    height: "6-2",
    weight: "170",
    draftPosition: "2020 TOR 4th (106)",
    photo: "imgs/Akhtyamov.png",
  },
  {
    firstName: "Matt",
    lastName: "Benning",
    position: "D",
    age: 30,
    height: "6-1",
    weight: "203",
    draftPosition: "2012 BOS 6th (175)",
    photo: "imgs/benning.png",
  },
  {
    firstName: "Simon",
    lastName: "Benoit",
    position: "D",
    age: 26,
    height: "6-4",
    weight: "211",
    draftPosition: "N/A",
    photo: "imgs/benoit.png",
  },
  {
    firstName: "Brandon",
    lastName: "Carlo",
    position: "D",
    age: 28,
    height: "6-5",
    weight: "220",
    draftPosition: "2015 BOS 2nd (37)",
    photo: "imgs/carlo.png",
  },
  {
    firstName: "Max",
    lastName: "Domi",
    position: "F",
    age: 29,
    height: "5-10",
    weight: "209",
    draftPosition: "2013 PHX 1st (12)",
    photo: "imgs/domi.png",
  },
  {
    firstName: "Oliver",
    lastName: "Ekman-Larsson",
    position: "D",
    age: 33,
    height: "6-2",
    weight: "192",
    draftPosition: "2009 PHX 1st (6)",
    photo: "imgs/ekman-larsson.png",
  },
  {
    firstName: "Dennis",
    lastName: "Hildeby",
    position: "G",
    age: 23,
    height: "6-7",
    weight: "224",
    draftPosition: "2022 TOR 4th (122)",
    photo: "imgs/hildebly.png",
  },
  {
    firstName: "Roni",
    lastName: "Hirvonen",
    position: "F",
    age: 23,
    height: "5-10",
    weight: "178",
    draftPosition: "2020 TOR 2nd (59)",
    photo: "imgs/hirvonen.png",
  },
  {
    firstName: "Pontus",
    lastName: "Holmberg",
    position: "F",
    age: 25,
    height: "6-0",
    weight: "201",
    draftPosition: "2018 TOR 6th (156)",
    photo: "imgs/holmberg.png",
  },
  {
    firstName: "Calle",
    lastName: "Jarnkrok",
    position: "F",
    age: 33,
    height: "6-0",
    weight: "191",
    draftPosition: "2010 DET 2nd (51)",
    photo: "imgs/jarnkrok.png",
  },
  {
    firstName: "Reese",
    lastName: "Johnson",
    position: "F",
    age: 26,
    height: "6-1",
    weight: "193",
    draftPosition: "N/A",
    photo: "imgs/johnson.png",
  },
  {
    firstName: "David",
    lastName: "Kampf",
    position: "F",
    age: 30,
    height: "6-2",
    weight: "193",
    draftPosition: "N/A",
    photo: "imgs/kampf.png",
  },
  {
    firstName: "Matthew",
    lastName: "Knies",
    position: "F",
    age: 22,
    height: "6-3",
    weight: "227",
    draftPosition: "2021 TOR 2nd (57)",
    photo: "imgs/knies.png",
  },
  {
    firstName: "Mikko",
    lastName: "Kokkonen",
    position: "D",
    age: 24,
    height: "6-0",
    weight: "200",
    draftPosition: "2019 TOR 3rd (84)",
    photo: "imgs/kokkonen.png",
  },
  {
    firstName: "Scott",
    lastName: "Laughton",
    position: "F",
    age: 30,
    height: "6-1",
    weight: "191",
    draftPosition: "2012 PHI 1st (20)",
    photo: "imgs/laughton.png",
  },
  {
    firstName: "Steven",
    lastName: "Lorentz",
    position: "F",
    age: 28,
    height: "6-4",
    weight: "216",
    draftPosition: "2015 CAR 7th (186)",
    photo: "imgs/lorentz.png",
  },
  {
    firstName: "Mitch",
    lastName: "Marner",
    position: "F",
    age: 27,
    height: "6-0",
    weight: "180",
    draftPosition: "2015 TOR 1st (4)",
    photo: "imgs/marner.png",
  },
  {
    firstName: "Auston",
    lastName: "Matthews",
    position: "F",
    age: 27,
    height: "6-3",
    weight: "217",
    draftPosition: "2016 TOR 1st (1)",
    photo: "imgs/matthews.png",
  },
  {
    firstName: "Jake",
    lastName: "McCabe",
    position: "D",
    age: 31,
    height: "6-1",
    weight: "212",
    draftPosition: "2012 BUF 2nd (44)",
    photo: "imgs/mccabe.png",
  },
  {
    firstName: "Bobby",
    lastName: "McMann",
    position: "F",
    age: 28,
    height: "6-2",
    weight: "215",
    draftPosition: "N/A",
    photo: "imgs/mcmann.png",
  },
  {
    firstName: "Dakota",
    lastName: "Mermis",
    position: "D",
    age: 31,
    height: "6-0",
    weight: "197",
    draftPosition: "N/A",
    photo: "imgs/mermis.png",
  },
  {
    firstName: "Matt",
    lastName: "Murray",
    position: "G",
    age: 30,
    height: "6-5",
    weight: "220",
    draftPosition: "2012 PIT 3rd (83)",
    photo: "imgs/murray.png",
  },
  {
    firstName: "Philippe",
    lastName: "Myers",
    position: "D",
    age: 28,
    height: "6-5",
    weight: "219",
    draftPosition: "2015 PHI 2nd (41)",
    photo: "imgs/myers.png",
  },
  {
    firstName: "Topi",
    lastName: "Niemela",
    position: "D",
    age: 22,
    height: "6-0",
    weight: "179",
    draftPosition: "2020 TOR 3rd (64)",
    photo: "imgs/niemela.png",
  },
  {
    firstName: "Alex",
    lastName: "Nylander",
    position: "F",
    age: 26,
    height: "6-1",
    weight: "192",
    draftPosition: "2016 BUF 1st (8)",
    photo: "imgs/a-nylander.png",
  },
  {
    firstName: "William",
    lastName: "Nylander",
    position: "F",
    age: 28,
    height: "6-0",
    weight: "202",
    draftPosition: "2014 TOR 1st (8)",
    photo: "imgs/w-nylander.png",
  },
  {
    firstName: "Max",
    lastName: "Pacioretty",
    position: "F",
    age: 36,
    height: "6-2",
    weight: "217",
    draftPosition: "2007 MTL 1st (22)",
    photo: "imgs/pacioretty.png",
  },
  {
    firstName: "Jacob",
    lastName: "Quillan",
    position: "F",
    age: 22,
    height: "6-1",
    weight: "204",
    draftPosition: "N/A",
    photo: "imgs/quillan.png",
  },
  {
    firstName: "Ryan",
    lastName: "Reaves",
    position: "F",
    age: 38,
    height: "6-2",
    weight: "225",
    draftPosition: "2005 STL 5th (156)",
    photo: "imgs/reaves.png",
  },
  {
    firstName: "Morgan",
    lastName: "Rielly",
    position: "D",
    age: 30,
    height: "6-1",
    weight: "225",
    draftPosition: "2012 TOR 1st (5)",
    photo: "imgs/rielly.png",
  },
  {
    firstName: "Marshall",
    lastName: "Rifai",
    position: "D",
    age: 26,
    height: "6-2",
    weight: "213",
    draftPosition: "N/A",
    photo: "imgs/rifai.png",
  },
  {
    firstName: "Nicholas",
    lastName: "Robertson",
    position: "F",
    age: 23,
    height: "5-9",
    weight: "178",
    draftPosition: "2019 TOR 2nd (53)",
    photo: "imgs/robertson.png",
  },
  {
    firstName: "Alex",
    lastName: "Steeves",
    position: "F",
    age: 25,
    height: "6-2",
    weight: "201",
    draftPosition: "N/A",
    photo: "imgs/steeves.png",
  },
  {
    firstName: "John",
    lastName: "Tavares",
    position: "F",
    age: 34,
    height: "6-1",
    weight: "219",
    draftPosition: "2009 NYI 1st (1)",
    photo: "imgs/tavares.png",
  },
  {
    firstName: "Anthony",
    lastName: "Stolarz",
    position: "G",
    age: 31,
    height: "6-6",
    weight: "243",
    draftPosition: "2012 PHI 2nd (45)",
    photo: "imgs/stolarz.png",
  },
  {
    firstName: "Christopher",
    lastName: "Tanev",
    position: "D",
    age: 35,
    height: "6-3",
    weight: "199",
    draftPosition: "N/A",
    photo: "imgs/tanev.png",
  },
  {
    firstName: "William",
    lastName: "Villeneuve",
    position: "D",
    age: 22,
    height: "6-2",
    weight: "183",
    draftPosition: "2020 TOR 4th (122)",
    photo: "imgs/villeneuve.png",
  },
  {
    firstName: "Cade",
    lastName: "Webber",
    position: "D",
    age: 24,
    height: "6-7",
    weight: "212",
    draftPosition: "2019 CAR 4th (99)",
    photo: "imgs/webber.png",
  },
  {
    firstName: "Joseph",
    lastName: "Woll",
    position: "G",
    age: 26,
    height: "6-3",
    weight: "206",
    draftPosition: "2016 TOR 3rd (62)",
    photo: "imgs/woll.png",
  },
];
